
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters: TokenRelay
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/Gafar
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: 3c8dacf8-2dde-4b59-ab87-4f7748e25ed0
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-url: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
