server:
  port: 0

spring:
  application:
    name: PRODUCT-SERVICE
  profiles:
    active: default
  cloud:
    config:
      profile: default
      name: product-service
  data:
    mongodb:
      uri: ${mongodb-u}
  sleuth:
    sampler:
      probability: 1.0
    circuitbreaker:
      enabled: false
  zipkin:
   base-url: http://localhost:9411/
  config:
    import: optional:configserver:http://localhost:8888


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: '*'
